<?php

use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints as Constraints;

/**
 * Skeleton subclass for representing a row from the 'book' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * Tue Feb 28 17:16:20 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Book extends BaseBook 
{
  // validation
  public static function loadValidatorMetadata(classMetadata $metadata)
  {
    $metadata->addPropertyConstraint('name', new Constraints\NotBlank());
    $metadata->addPropertyConstraint('name', new Constraints\MinLength(10));
    $metadata->addPropertyConstraint('name', new Constraints\MaxLength(30));
  }

} // Book
