<?php



/**
 * Skeleton subclass for representing a row from the 'product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * Tue Feb 28 17:16:21 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Product extends BaseProduct {

} // Product
